name: CI/CDworkflof
'on':
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions
            - name: Set up Node.js dependencies
              uses: actions/setup-node@v2
              with:
                node-version: 12
            - name: Install Node.js dependencies
              run: npm ci
            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                eslint: true
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: astr001
                password: dckr_pat_zmZSURIZrKLcNjE6ofskJmcG_js
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                push: true
                tags: 'user/app:latest'